#!/usr/bin/env python
from __future__ import print_function

import argparse
import dxpy
import fnmatch
import json
import pprint
import os
import subprocess
import sys
import time

top_dir = os.path.dirname(sys.argv[0])
version_id = None
asset_id = None
project_id = None
lib_object_ids = None
required_libs = ["dnanexus-api-0.1.0-SNAPSHOT-jar-with-dependencies.jar",
                 "dxWDL.jar"]

def prolog(args):
    global asset_id
    global version_id

    # Figure out the asset ID
    if args.asset is not None:
        asset_id = args.asset
    if asset_id is None:
        print("Asset ID is undefined", file=sys.stderr)
        exit(1)

    jars = construct_java_classpath()
    classpath = ":".join(jars)

    if version_id is not None:
        version_id = version_id.strip()
        validate_library_version(version_id, classpath)
        validate_asset_version(version_id, asset_id)
    return [asset_id, classpath]


# Check if the local library has the correct version
def validate_library_version(version_id, classpath):
    cmd_line = ["java", "-cp", classpath, "dxWDL.Main", "version"]
    outstr = subprocess.check_output(cmd_line)
    lib_version_id = outstr.rstrip().split('\n')[-1].strip()
    if lib_version_id != version_id:
        print("Local jar files have incorrect version {}, should be {}".
              format(lib_version_id, version_id), file=sys.stderr)
        print("Please remove the local jar files, and rerun dxWDL.", file=sys.stderr)
        print("It will download the correct version from the platform.", file=sys.stderr)
        exit(1)

# Make sure the asset we point to, has the correct version
def validate_asset_version(version_id, asset_id):
    record = dxpy.DXRecord(asset_id)
    desc = record.describe(incl_properties=True)
    props = desc["properties"]
    pkg_version_id = props["version"].strip()
    if version_id == pkg_version_id:
        print("version={}".format(version_id), file=sys.stderr)
    else:
        print("Asset version number mismatch, local={}, platform={}".format(version_id, pkg_version_id))
        exit(1)

# Build a workflow.
#
# wf             workflow name
# classpath      java classpath needed for running compilation
# destination    output path on the platform
#
# return --      workflow ID
def compile_workflow(wf_file, wdl_input_file, destination, asset_id, classpath, force, verbose, mode):
    print("Compiling {}".format(wf_file), file=sys.stderr)
    cmd_line = [
        "java", "-cp", classpath, "dxWDL.Main", "compile", wf_file,
        "-o", destination,
        "-asset", asset_id
    ]
    if wdl_input_file is not None:
        cmd_line += ["-inputFile", wdl_input_file]
    if version_id is not None:
        cmd_line += ["-expected_version", version_id]
    if force:
        cmd_line += ["-force"]
    if verbose:
        cmd_line += ["-verbose"]
    if mode:
        cmd_line += ["-mode", mode]
    return call_compiler(cmd_line)


# Search for the jars locally. If not found, download
# from the platform.
def construct_java_classpath():
    classpath = lookup_local_jars()
    if classpath is not None:
        return classpath
    download_libs()
    classpath = lookup_local_jars()
    if classpath is None:
        print("Error, could not find jars, after download", file=sys.stderr)
        exit(1)
    return classpath

# Download libraries from the platform
def download_libs():
    if (lib_object_ids is None or
        len(lib_object_ids) == 0):
        print("Can't download libraries, download objects are not set", file=sys.stderr)
        exit(1)

    # We don't have all jars locally. Download them from the platform.
    for fid in lib_object_ids:
        dxfile = dxpy.DXFile(fid, project=project_id)
        name = dxfile.describe()["name"]
        print("downloading {}".format(name), file=sys.stderr)
        dxpy.download_dxfile(fid, os.path.join(top_dir, name))

def lookup_local_jars():
    [jar_names, jar_paths] = find('*.jar', top_dir)
    print("found {}".format(jar_names), file=sys.stderr)
    classpath = []
    for lib in required_libs:
        if lib in jar_names:
            index = jar_names.index(lib)
            classpath.append(jar_paths[index])
        else:
            print("Not found {}".format(lib), file=sys.stderr)
            return None
    return classpath

# Find all files that match regular expression [pattern]
# starting from [path]
def find(pattern, path):
    names = []
    paths = []
    for root, dirs, files in os.walk(path):
        for name in files:
            if fnmatch.fnmatch(name, pattern):
                names.append(name)
                paths.append(os.path.join(root, name))
    return [names, paths]

# Run the compiler in a different process, and wait for completion
def call_compiler(cmd_line):
    print((" ".join(cmd_line)), file=sys.stderr)

    # Call java/scala dxWDL compiler, and pipe stdout/stderr
    outstr = subprocess.check_output(cmd_line)
    retval = outstr.rstrip().split('\n')[-1]
    return retval


def cmd_compile(args):
    # Where should we write the result?
    if args.destination is None:
        destination = dxpy.config.get('DX_CLI_WD', u'/')
    else:
        destination = args.destination
    [asset_id, classpath] = prolog(args)
    compile_workflow(args.wdl_file, args.wdl_input_file,
                     destination, asset_id, classpath,
                     args.force, args.verbose, args.mode)


######################################################################
# Command line parsing

# Top level parser
parser = argparse.ArgumentParser(description="Tool for compiling and running WDL source files on the platform")
subparsers = parser.add_subparsers(help=argparse.SUPPRESS, dest='command')
subparsers.metavar = 'command'

# Parser for the compile command
compile_parser = subparsers.add_parser('compile',
                                       help="compile a WDL file to a platform applet/workflow",
                                       description="compile a WDL file to a platform applet/workflow")
compile_parser.add_argument("wdl_file", help="WDL workflow file")
compile_parser.add_argument("--asset", help="Override configuration file asset Id")
compile_parser.add_argument("--destination", help="Output folder for workflow")
compile_parser.add_argument("--wdl_input_file", help="WDL input file")
compile_parser.add_argument("--mode", help="Compilation mode, a debugging flag")
compile_parser.add_argument("--verbose", dest='verbose', action='store_true', default=False,
                            help="Print detailed progress reports")
compile_parser.add_argument("--force", dest='force', action='store_true', default=False,
                            help="Always rebuild applets")
compile_parser.set_defaults(func=cmd_compile)

# Parser for the run command
# TODO
######################################################################

# Program entry point
def main():
    args_list = sys.argv[1:]
    if len(args_list) > 0:
        args = parser.parse_args(args_list)
        args.func(args)
    else:
        parser.print_help()
        sys.exit(1)

if __name__ == '__main__':
    main()
