package dx.dxni

import java.nio.file.{Files, Path}

import dx.api._
import dx.core.Native
import dx.core.getVersion
import dx.core.languages.Language.Language
import dx.dxni.wdl.WdlDxNativeInterfaceFactory
import wdlTools.util.{FileSourceResolver, FileUtils}

case class DxNativeInterface(fileResolver: FileSourceResolver = FileSourceResolver.get,
                             dxApi: DxApi = DxApi.get) {

  private val generatorFactories = Vector(
      WdlDxNativeInterfaceFactory(fileResolver = fileResolver, dxApi = dxApi)
  )

  private def getGenerator(language: Language): NativeInterfaceGenerator = {
    generatorFactories
      .collectFirst { factory =>
        factory.create(language) match {
          case Some(support) => support
        }
      }
      .getOrElse(
          throw new Exception(s"Language ${language} is not supported")
      )
  }

  private def getApplet(dxProject: DxProject, path: String): DxApplet = {
    path match {
      case id if id.startsWith("applet-") => dxApi.applet(id)
      case _ =>
        dxApi.resolveOnePath(path, Some(dxProject)) match {
          case applet: DxApplet => applet
          case _                => throw new Exception(s"DxNI only supports apps and applets")
        }
    }
  }

  private def searchApplets(dxProject: DxProject,
                            folder: String,
                            recursive: Boolean): Vector[DxApplet] = {
    val applets: Vector[DxApplet] =
      DxFindDataObjects(dxApi)
        .apply(Some(dxProject),
               Some(folder),
               recursive,
               classRestriction = Some("applet"),
               withInputOutputSpec = true)
        .keySet
        .collect {
          case applet: DxApplet
              if applet
                .describe(Set(Field.Details))
                .details
                .exists(_.asJsObject.fields.contains(Native.Checksum)) =>
            applet
        }
        .toVector
    if (applets.isEmpty) {
      dxApi.logger.trace(s"Found no applets in project ${dxProject.id}/${folder}")
    }
    applets
  }

  private def searchApps: Vector[DxApp] = {
    val apps: Vector[DxApp] = DxFindApps(dxApi)
      .apply(published = Some(true), withInputOutputSpec = true)
    if (apps.isEmpty) {
      dxApi.logger.warning(s"Found no DX global apps")
    }
    apps
  }

  private def writeToFile(doc: Vector[String], outputPath: Path, force: Boolean): Unit = {
    if (Files.exists(outputPath)) {
      if (!force) {
        throw new Exception(
            s"Output file ${outputPath.toString} already exists, use -force to overwrite it"
        )
      }
      outputPath.toFile.delete
    }
    FileUtils.writeFileContent(outputPath, doc.mkString("\n"))
  }

  private val appsHeader = Vector(
      s"This file was generated by the Dx Native Interface (DxNI) tool ${getVersion}.",
      "These are interfaces to apps."
  )

  /**
    * Generate only apps.
    * @param output output file
    * @param force overwrite existing file
    */
  def apply(language: Language, output: Path, force: Boolean): Unit = {
    val generator = getGenerator(language)
    val apps = searchApps
    if (apps.nonEmpty) {
      val doc = generator.generate(apps, headerLines = appsHeader)
      if (doc.nonEmpty) {
        writeToFile(doc, output, force)
      }
    }
  }

  private def appletsHeader(dxProject: DxProject, path: String) = Vector(
      s"This file was generated by the Dx Native Interface (DxNI) tool ${getVersion}.",
      s"project name = ${dxProject.describe().name}",
      s"project ID = ${dxProject.getId}",
      s"path = ${path}"
  )

  def apply(language: Language,
            output: Path,
            dxProject: DxProject,
            folder: Option[String] = None,
            path: Option[String] = None,
            applet: Option[DxApplet] = None,
            recursive: Boolean = false,
            force: Boolean = false): Unit = {
    val generator = getGenerator(language)
    val apps = searchApps
    val (applets: Vector[DxApplet], search) = (folder, path, applet) match {
      case (Some(folder), None, None) => (searchApplets(dxProject, folder, recursive), folder)
      case (None, Some(path), None)   => (Vector(getApplet(dxProject, path)), path)
      case (None, None, Some(applet)) => (Vector(applet), applet.id)
      case _                          => throw new Exception("must specify exactly one of (folder, path)")
    }
    val doc = generator.generate(apps, applets, appletsHeader(dxProject, search))
    if (doc.nonEmpty) {
      writeToFile(doc, output, force)
    }
  }
}
