# This file was generated by the Dx Native Interface (DxNI) tool.
# project name = dxWDL_playground
# project ID = project-FGpfqjQ0ffPF1Q106JYP2j3v
# folder = /builds/0.90/applets



task native_sum_012 {
    Int? a
    Int? b

  command {}
  output {
    Int result = 0
  }
  meta {
     type : "native"
     id : "applet-FXgvJ580ffP1ZjfxFF3xQp6b"
  }
}

task native_sum {
    Int? a
    Int? b

  command {}
  output {
    Int result = 0
  }
  meta {
     type : "native"
     id : "applet-FXgvJ500ffP1KBfJFBjQvzj9"
  }
}

task native_mk_list {
    Int a
    Int b

  command {}
  output {
    Array[Int]+ all = [0]
  }
  meta {
     type : "native"
     id : "applet-FXgvJ4j0ffPJKFpxFfxX91kj"
  }
}

task native_diff {
    File a
    File b

  command {}
  output {
    Boolean equality = true
  }
  meta {
     type : "native"
     id : "applet-FXgvJ4Q0ffP1KBfJFBjQvzj7"
  }
}

task native_concat {
    String? a
    String? b

  command {}
  output {
    String c = ""
  }
  meta {
     type : "native"
     id : "applet-FXgvJ400ffPBxJGBF9kVf1kY"
  }
}