# This file was generated by the Dx Native Interface (DxNI) tool.
# project name = dxWDL_playground
# project ID = project-FGpfqjQ0ffPF1Q106JYP2j3v
# folder = path = /builds/orodeh/v1.44/applets/native_concat

version 1.0

task native_concat {
  input {
    String? a
    String? b
  }
  command {}
  output {
    String c = ""
  }
  meta {
     type : "native"
     id : "applet-Fk81QkQ0ffPKfZVPPYjjjBb3"
  }
}