# This file was generated by the Dx Native Interface (DxNI) tool.
# project name = dxWDL_playground
# project ID = project-F07pBj80ZvgfzQK28j35Gj54
# folder = /builds/2018-02-08/154002-0.59-10-gd9fd68c/applets

task native_concat {
    String? a 
    String? b 
    command {
    }
    output {
        String c = ""
    }
    meta {
        type: "native" 
        id: "applet-F9yK0zQ0ZvgVPV0V5g866220" 
    }
}
task native_diff {
    File a 
    File b 
    command {
    }
    output {
        Boolean equality = true
    }
    meta {
        type: "native" 
        id: "applet-F9yK0zj0ZvgjXf3k5gPJj546" 
    }
}
task native_mk_list {
    Int a 
    Int b 
    command {
    }
    output {
        Array[Int]+ all = [0]
    }
    meta {
        type: "native" 
        id: "applet-F9yK1000ZvgjXf3k5gPJj548" 
    }
}
task native_sum {
    Int? a 
    Int? b 
    command {
    }
    output {
        Int result = 0
    }
    meta {
        type: "native" 
        id: "applet-F9yK1080ZvgjXf3k5gPJj54F" 
    }
}
task native_sum_012 {
    Int? a 
    Int? b 
    command {
    }
    output {
        Int result = 0
    }
    meta {
        type: "native" 
        id: "applet-F9yKKZ80ZvgxPkJy101PQkJj" 
    }
}